# Generated by Django 5.0.6 on 2024-05-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("CREATE EXTENSION IF NOT EXISTS pgcrypto;"),
                ("CREATE SCHEMA IF NOT EXISTS master;"),
                ("""
                    CREATE TABLE IF NOT EXISTS master.pockets (
                        pocket_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                        user_id UUID REFERENCES master.users(user_id),
                        name VARCHAR(255) NOT NULL,
                        type VARCHAR(255),
                        created_at TIMESTAMP DEFAULT current_timestamp
                    );
                 """)
            ],
            reverse_sql=[
                ("DROP TABLE IF EXISTS master.pockets;"),
                ("DROP EXTENSION IF EXISTS pgcrypto;")
            ]
        )
    ]
