# Generated by Django 5.0.6 on 2024-05-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("CREATE EXTENSION IF NOT EXISTS pgcrypto;"),
                ("CREATE SCHEMA IF NOT EXISTS transaction;"),
                ("""
                    CREATE TABLE IF NOT EXISTS transaction.transactions (
                        transaction_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                        user_id UUID REFERENCES master.users(user_id),
                        pocket_id UUID REFERENCES master.pockets(pocket_id),
                        amount DECIMAL(10, 2) NOT NULL,
                        type VARCHAR(255) NOT NULL,
                        category VARCHAR(255),
                        description TEXT,
                        transaction_date TIMESTAMP NOT NULL,
                        created_at TIMESTAMP DEFAULT current_timestamp
                    );
                 """)
            ],
            reverse_sql=[
                ("DROP TABLE IF EXISTS transaction.transactions;"),
                ("DROP EXTENSION IF EXISTS pgcrypto;")
            ]
        )
    ]
